// Code generated by protoc-gen-go. DO NOT EDIT.
// source: canteen_management.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GoodsInfoExtra struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoodsInfoExtra) Reset()         { *m = GoodsInfoExtra{} }
func (m *GoodsInfoExtra) String() string { return proto.CompactTextString(m) }
func (*GoodsInfoExtra) ProtoMessage()    {}
func (*GoodsInfoExtra) Descriptor() ([]byte, []int) {
	return fileDescriptor_canteen_management_307db76e7478c8cf, []int{0}
}
func (m *GoodsInfoExtra) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoodsInfoExtra.Unmarshal(m, b)
}
func (m *GoodsInfoExtra) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoodsInfoExtra.Marshal(b, m, deterministic)
}
func (dst *GoodsInfoExtra) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoodsInfoExtra.Merge(dst, src)
}
func (m *GoodsInfoExtra) XXX_Size() int {
	return xxx_messageInfo_GoodsInfoExtra.Size(m)
}
func (m *GoodsInfoExtra) XXX_DiscardUnknown() {
	xxx_messageInfo_GoodsInfoExtra.DiscardUnknown(m)
}

var xxx_messageInfo_GoodsInfoExtra proto.InternalMessageInfo

func (m *GoodsInfoExtra) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*GoodsInfoExtra)(nil), "GoodsInfoExtra")
}

func init() {
	proto.RegisterFile("canteen_management.proto", fileDescriptor_canteen_management_307db76e7478c8cf)
}

var fileDescriptor_canteen_management_307db76e7478c8cf = []byte{
	// 90 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x48, 0x4e, 0xcc, 0x2b,
	0x49, 0x4d, 0xcd, 0x8b, 0xcf, 0x4d, 0xcc, 0x4b, 0x4c, 0x4f, 0xcd, 0x4d, 0xcd, 0x2b, 0xd1, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x57, 0x52, 0xe1, 0xe2, 0x73, 0xcf, 0xcf, 0x4f, 0x29, 0xf6, 0xcc, 0x4b,
	0xcb, 0x77, 0xad, 0x28, 0x29, 0x4a, 0x14, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60,
	0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x93, 0xd8, 0xc0, 0x8a, 0x8d, 0x01, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xe8, 0x55, 0x53, 0xd0, 0x48, 0x00, 0x00, 0x00,
}
