// Code generated by protoc-gen-go. DO NOT EDIT.
// source: canteen_management.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GoodsInfoExtra struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoodsInfoExtra) Reset()         { *m = GoodsInfoExtra{} }
func (m *GoodsInfoExtra) String() string { return proto.CompactTextString(m) }
func (*GoodsInfoExtra) ProtoMessage()    {}
func (*GoodsInfoExtra) Descriptor() ([]byte, []int) {
	return fileDescriptor_canteen_management_3f08c49beb299d41, []int{0}
}
func (m *GoodsInfoExtra) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoodsInfoExtra.Unmarshal(m, b)
}
func (m *GoodsInfoExtra) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoodsInfoExtra.Marshal(b, m, deterministic)
}
func (dst *GoodsInfoExtra) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoodsInfoExtra.Merge(dst, src)
}
func (m *GoodsInfoExtra) XXX_Size() int {
	return xxx_messageInfo_GoodsInfoExtra.Size(m)
}
func (m *GoodsInfoExtra) XXX_DiscardUnknown() {
	xxx_messageInfo_GoodsInfoExtra.DiscardUnknown(m)
}

var xxx_messageInfo_GoodsInfoExtra proto.InternalMessageInfo

func (m *GoodsInfoExtra) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type FlowingWaterExtra struct {
	GoodsID              uint64   `protobuf:"varint,1,opt,name=goodsID" json:"goodsID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FlowingWaterExtra) Reset()         { *m = FlowingWaterExtra{} }
func (m *FlowingWaterExtra) String() string { return proto.CompactTextString(m) }
func (*FlowingWaterExtra) ProtoMessage()    {}
func (*FlowingWaterExtra) Descriptor() ([]byte, []int) {
	return fileDescriptor_canteen_management_3f08c49beb299d41, []int{1}
}
func (m *FlowingWaterExtra) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlowingWaterExtra.Unmarshal(m, b)
}
func (m *FlowingWaterExtra) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlowingWaterExtra.Marshal(b, m, deterministic)
}
func (dst *FlowingWaterExtra) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlowingWaterExtra.Merge(dst, src)
}
func (m *FlowingWaterExtra) XXX_Size() int {
	return xxx_messageInfo_FlowingWaterExtra.Size(m)
}
func (m *FlowingWaterExtra) XXX_DiscardUnknown() {
	xxx_messageInfo_FlowingWaterExtra.DiscardUnknown(m)
}

var xxx_messageInfo_FlowingWaterExtra proto.InternalMessageInfo

func (m *FlowingWaterExtra) GetGoodsID() uint64 {
	if m != nil {
		return m.GoodsID
	}
	return 0
}

type UserInfoExtra struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoExtra) Reset()         { *m = UserInfoExtra{} }
func (m *UserInfoExtra) String() string { return proto.CompactTextString(m) }
func (*UserInfoExtra) ProtoMessage()    {}
func (*UserInfoExtra) Descriptor() ([]byte, []int) {
	return fileDescriptor_canteen_management_3f08c49beb299d41, []int{2}
}
func (m *UserInfoExtra) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoExtra.Unmarshal(m, b)
}
func (m *UserInfoExtra) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoExtra.Marshal(b, m, deterministic)
}
func (dst *UserInfoExtra) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoExtra.Merge(dst, src)
}
func (m *UserInfoExtra) XXX_Size() int {
	return xxx_messageInfo_UserInfoExtra.Size(m)
}
func (m *UserInfoExtra) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoExtra.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoExtra proto.InternalMessageInfo

func (m *UserInfoExtra) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*GoodsInfoExtra)(nil), "GoodsInfoExtra")
	proto.RegisterType((*FlowingWaterExtra)(nil), "FlowingWaterExtra")
	proto.RegisterType((*UserInfoExtra)(nil), "UserInfoExtra")
}

func init() {
	proto.RegisterFile("canteen_management.proto", fileDescriptor_canteen_management_3f08c49beb299d41)
}

var fileDescriptor_canteen_management_3f08c49beb299d41 = []byte{
	// 131 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x48, 0x4e, 0xcc, 0x2b,
	0x49, 0x4d, 0xcd, 0x8b, 0xcf, 0x4d, 0xcc, 0x4b, 0x4c, 0x4f, 0xcd, 0x4d, 0xcd, 0x2b, 0xd1, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x57, 0x52, 0xe1, 0xe2, 0x73, 0xcf, 0xcf, 0x4f, 0x29, 0xf6, 0xcc, 0x4b,
	0xcb, 0x77, 0xad, 0x28, 0x29, 0x4a, 0x14, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60,
	0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95, 0x74, 0xb9, 0x04, 0xdd, 0x72, 0xf2, 0xcb, 0x33,
	0xf3, 0xd2, 0xc3, 0x13, 0x4b, 0x52, 0x8b, 0x20, 0x0a, 0x25, 0xb8, 0xd8, 0xd3, 0xc1, 0x5a, 0x5d,
	0xc0, 0x6a, 0x59, 0x82, 0x60, 0x5c, 0x25, 0x65, 0x2e, 0xde, 0xd0, 0xe2, 0xd4, 0x22, 0xbc, 0x66,
	0x26, 0xb1, 0x81, 0x1d, 0x60, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x44, 0x21, 0x42, 0x52, 0x9c,
	0x00, 0x00, 0x00,
}
